// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodels

var TableNames = struct {
	Accounts         string
	Products         string
	SchemaMigrations string
}{
	Accounts:         "accounts",
	Products:         "products",
	SchemaMigrations: "schema_migrations",
}
