// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewAccount struct {
	Username string `json:"username"`
	Password int    `json:"password"`
}

type UpdateAccountModel struct {
	ID       int    `json:"id"`
	Username string `json:"username"`
	Password int    `json:"password"`
}
