// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ItemModel struct {
	ID        string `json:"id"`
	Code      string `json:"code"`
	Productid int    `json:"productid"`
	Unit      int    `json:"unit"`
	Price     string `json:"price"`
	Total     string `json:"total"`
}
type NewItem struct {
	Code      string `json:"code"`
	Productid int    `json:"productid"`
	Unit      int    `json:"unit"`
	Price     string `json:"price"`
	Total     string `json:"total"`
}
