// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"graphdemo/pkg/entity"
)



type NewOrder struct {
	Accountid int          `json:"accountid"`
	Items     []*ItemModel `json:"items"`
	Total     int          `json:"total"`
}

type Order struct {
	ID        string         `json:"id"`
	Accountid int            `json:"accountid"`
	Items     []*entity.Item `json:"items"`
	Total     int            `json:"total"`
}

type UpdateOrderModel struct {
	ID    int          `json:"id"`
	Items []*ItemModel `json:"items"`
	Total int          `json:"total"`
}

