// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model


type NewOrder struct {
	Accountid int          `json:"accountid"`
	Items     []*ItemModel `json:"items"`
	Total     int          `json:"total"`
}




type UpdateOrderModel struct {
	ID    int          `json:"id"`
	Items []*ItemModel `json:"items"`
	Total int          `json:"total"`
}
