// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewProduct struct {
	Code        string `json:"code"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Price       string `json:"price"`
	Category    string `json:"category"`
}


type UpdateProductModel struct {
	ID          int    `json:"id"`
	Code        string `json:"code"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Price       string `json:"price"`
	Category    string `json:"category"`
}
