// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Accounts struct {
	ID       int `json:"id"`
	Username string `json:"username"`
	Password int    `json:"password"`
}

type NewAccount struct {
	Username string `json:"username"`
	Password int    `json:"password"`
}
